const express       = require('express');
const cookieParser  = require('cookie-parser');
const bodyParser    = require('body-parser');
const morgan        = require('morgan');
const path          = require('path');
const session       = require('express-session');
const dotenv        = require('dotenv');
const passport      = require('passport'); 
const { sequelize } = require('./src/models');