version: '3'
services:

  api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    env_file:
      - ./server/.env
    ports:
      - "5000:5000"
    image: poodly/mianri-dockerhub:dev_0.0.3_server